# Generated by Django 4.1.2 on 2022-10-31 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursecategory",
            name="featuredImage",
            field=models.ImageField(
                default="defaultBG.png", upload_to="uploads/images"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_collection",
                to="course.coursecategory",
            ),
        ),
    ]
