# Generated by Django 4.1.2 on 2022-10-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(default="")),
                ("keywords", models.CharField(default="", max_length=400)),
                ("metaDesc", models.CharField(default="", max_length=400)),
            ],
        ),
    ]
