# Generated by Django 4.1.2 on 2022-10-30 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_coursecategory"),
    ]

    operations = [
        migrations.DeleteModel(name="CourseCategory",),
    ]
